/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Sara
 * Created: 23-mag-2016
 */

--Creazione delle tabelle
CREATE TABLE saldoConto (
    idConto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saldo DOUBLE PRECISION
);

CREATE TABLE cliente(
    idCliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userCliente VARCHAR (64),
    pswCliente VARCHAR (64),
    idContoC INTEGER,
    FOREIGN KEY (idContoC) REFERENCES saldoConto(idConto)
);

CREATE TABLE venditore(
    idVenditore INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userVenditore VARCHAR (64),
    pswVenditore VARCHAR (64),
    idContoV INTEGER,
    FOREIGN KEY (idContoV) REFERENCES saldoConto(idConto)
);

CREATE TABLE oggettiVendita(
    idOggetto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeOgg VARCHAR (64),
    urlOgg VARCHAR (64),
    descrizioneOgg VARCHAR (64),
    prezzoOgg DOUBLE PRECISION,
    quantitaOgg INTEGER,
    idVenditoreOgg INTEGER,
    FOREIGN KEY (idVenditoreOgg) REFERENCES venditore(idVenditore)
);

--Popolamento delle tabelle
INSERT INTO saldoConto(idConto, saldo)
VALUES  (default, 500.00),
        (default, 600.00),
        (default, 300.00),
        (default, 80.00),
        (default, 50.00);

INSERT INTO cliente(idCliente, userCliente, pswCliente, idContoC)
VALUES  (default, 'Black77', '98765', 99),
        (default, 'Anna88', 'giggetto', 140);

INSERT INTO venditore(idVenditore, userVenditore, pswVenditore, idContoV)
VALUES  (default, 'Giovanni85', '123345', 125),
        (default, 'Vanessa12', 'tartaruga90', 95),
        (default, 'Francesca.S', 'pippo', 80);

INSERT INTO oggettiVendita(idOggetto, nomeOgg, urlOgg, descrizioneOgg, prezzoOgg, quantitaOgg, idVenditoreOgg)
VALUES  (default, 'Fondotinta biologico - PuroBio Cosmetics', 'img/fondotinta_purobio_cosmetics.jpg',
                    'Fondotinta liquido biologico', 13.90, 10, 1),
        (default, 'Shade Fusion Trio Blush -Kiko Cosmetics', 'img/blush_kiko.png',
                    'Blush kiko', 8.90, 15, 1),
        (default, 'Palette Chocolate Bar - Too Faced', 'img/chocolate_bar_too_faced.jpg',
                    'Palette ombretti', 45.00, 5, 2),
        (default, 'Mascara volume I Love Extreme - Essence', 'img/I_love_extreme_volume_mascara.png',
                    'Mascara', 3.29, 20, 2),
        (default, 'Rossetto Ruby Woo - MAC Cosmetics', 'img/red-lipstick-MAC-Ruby-Woo.jpg',
                    'Rossetto rosso', 45.00, 5, 3);

        